#!/bin/bash

# Define the script paths
SERVER_START_SCRIPT="$(pwd)/scripts/server-start.sh"
SERVER_STOP_SCRIPT="$(pwd)/scripts/server-stop.sh"

echo $(pwd)
# Define the alias for pipe-start
alias pipe-start="bash $SERVER_START_SCRIPT"

# Define the alias for pipe-stop
alias pipe-stop="bash $SERVER_STOP_SCRIPT"

# Print a message to indicate that aliases are defined
echo "Aliases 'pipe-start' and 'pipe-stop' have been set."
echo "'pipe-start' : Start the Kafka servers."
echo "'pipe-stop' : Stop the Kafka servers."

# Source the script to activate the aliases
source ~/.bashrc